name: build
on: 
  push:
    paths-ignore:
    - 'README.md'
    - 'LICENSE'
jobs: 
  build:
    runs-on: macos-10.15
    strategy:
      max-parallel: 2
      matrix:  
        configuration: [Debug, Release]
        target: [cartool]
        arch: [x86_64] 
        sdk: [macosx]
    steps:
    - uses: actions/checkout@v2
    - run: |
        xcodebuild -project Cartools.xcodeproj \
          -target ${{ matrix.target }} \
          -configuration ${{ matrix.configuration }} \
          -arch ${{ matrix.arch }} \
          -sdk ${{ matrix.sdk }}